ALTER TABLE jobs ADD COLUMN cron_expr TEXT;
ALTER TABLE jobs ADD COLUMN cron_tz TEXT NOT NULL DEFAULT 'UTC';
ALTER TABLE jobs ADD COLUMN series_id UUID;
ALTER TABLE jobs ADD COLUMN is_recurring BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX IF NOT EXISTS jobs_series_idx ON jobs (series_id) WHERE series_id IS NOT NULL;
