DROP INDEX IF EXISTS jobs_series_idx;
ALTER TABLE jobs DROP COLUMN IF EXISTS is_recurring;
ALTER TABLE jobs DROP COLUMN IF EXISTS series_id;
ALTER TABLE jobs DROP COLUMN IF EXISTS cron_tz;
ALTER TABLE jobs DROP COLUMN IF EXISTS cron_expr;
